[options]
addons_path = /mnt/extra-addons/custom_addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
admin_passwd = 'xj+EXUNYgRqZR3gpbWecCHPK+wUU1+8e29H1t/Ge070='
db_password = odoo