{
    "name": "Gym Management System",
    "version": "1.0.0",
    "category": "Gym Management",
    "description": "Gym Management",
    "sequence": -99,
    "depends": ["mail", "product", "sale"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "views/coach_view.xml",
        "views/trainee_view.xml",
        "views/membership_view.xml",
        "views/session_view.xml",
        "views/product_views.xml",
        "views/menu.xml",
    ],
    "demo": [],
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
